language: node_js

node_js:
  - "8"

cache: npm

before_script:
  - npm install -g truffle
  - npm install -g ganache-cli

  
script:
  - ganache-cli -p 7545 > /dev/null &
  - sleep 5
  - npm run test
